version: '3'

services:
  app:
    image: 'currency-exchange-converter'
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cec?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_DATASOURCE_DRIVERCLASSNAME=com.mysql.jdbc.Driver
    ports:
      - "8082:8082"
  db:
    image: 'mysql:5.7'
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=cec
    ports:
      - "3306:3306"